import { ClassOfService, DemandType } from './types';

export interface ErpCardTemplate {
  id: string;
  module: 'finance' | 'stock' | 'sales' | 'fiscal' | 'pos';
  moduleLabel: string;
  title: string;
  description: string;
  demandType: DemandType;
  classOfService: ClassOfService;
  baseValue: number;
  effortAnalysis: number;
  effortDev: number;
  effortTest: number;
  deadlineDays: number;
  penaltyPerDay: number;
  accumulatedDocCost?: number;
  docCostPerDay?: number;
}

export const ERP_BUSINESS_CATALOG: ErpCardTemplate[] = [
  // =========================================================================
  // 💰 Módulo de Gestão Financeira e Fluxo de Caixa (7 cards)
  // =========================================================================
  {
    id: 'erp-fin-01',
    module: 'finance',
    moduleLabel: '💰 Gestão Financeira',
    title: 'Automação de Liquidação Bancária via Retorno de Pagamentos',
    description: 'Desenvolver o motor de processamento de arquivos de retorno bancário (CNAB), realizando o cruzamento automático de títulos, valores líquidos, taxas bancárias e abatimento de juros ou multas sem intervenção manual.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 3400,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 500,
  },
  {
    id: 'erp-fin-02',
    module: 'finance',
    moduleLabel: '💰 Gestão Financeira',
    title: 'Gestão e Reconciliação de Administradoras de Cartão',
    description: 'Implementar o módulo centralizado para controle de operadoras de crédito, gerenciando taxas de antecipação, prazos de repasse e o vínculo de documentos fiscais para garantir a acuracidade do fluxo de caixa projetado.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2800,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 350,
  },
  {
    id: 'erp-fin-03',
    module: 'finance',
    moduleLabel: '💰 Gestão Financeira',
    title: 'Conferência, Batimento de Caixa e Gestão de Quebras',
    description: 'Criar a rotina de fechamento de turno em pontos de atendimento, realizando o batimento entre o saldo teórico (dinheiro, PIX, cartões) e o saldo físico apurado, com controle de sangrias e suprimentos.',
    demandType: 'support',
    classOfService: 'standard',
    baseValue: 2200,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 280,
  },
  {
    id: 'erp-fin-04',
    module: 'finance',
    moduleLabel: '💰 Gestão Financeira',
    title: 'Estruturação de Centros de Custo e Rateio de Despesas',
    description: 'Implementar a lógica de distribuição percentual de despesas corporativas entre múltiplos departamentos e unidades de negócio, permitindo visões analíticas e sintéticas da rentabilidade.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2600,
    effortAnalysis: 3,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 8,
    penaltyPerDay: 300,
  },
  {
    id: 'erp-fin-05',
    module: 'finance',
    moduleLabel: '💰 Gestão Financeira',
    title: 'Gestão de Títulos Protestados e Cobrança Cartorária',
    description: 'Desenvolver o fluxo de encaminhamento de títulos vencidos para cobrança extrajudicial e cartório, atualizando status de inadimplência e controlando custos adicionais de recuperação de crédito.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 3100,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 450,
  },
  {
    id: 'erp-fin-06',
    module: 'finance',
    moduleLabel: '💰 Gestão Financeira',
    title: 'Projeção Dinâmica de Fluxo de Caixa Futuro',
    description: 'Criar painel preditivo que cruza contas a pagar, contas a receber e previsões de vendas para alertar a tesouraria sobre potenciais déficits de liquidez nos próximos períodos.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 3500,
    effortAnalysis: 3,
    effortDev: 5,
    effortTest: 2,
    deadlineDays: 8,
    penaltyPerDay: 400,
  },
  {
    id: 'erp-fin-07',
    module: 'finance',
    moduleLabel: '💰 Gestão Financeira',
    title: 'Alçada de Aprovação de Pagamentos por Limite de Valor',
    description: 'Implementar travas de segurança e fluxo de aprovação hierárquica para liberação de ordens de pagamento no Contas a Pagar de acordo com a alçada de cada gestor.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 2900,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 350,
  },

  // =========================================================================
  // 📦 Módulo de Estoque e Suprimentos (7 cards)
  // =========================================================================
  {
    id: 'erp-stk-01',
    module: 'stock',
    moduleLabel: '📦 Estoque & Suprimentos',
    title: 'Sistema de Grade de Produtos e Variações (Pai/Filho)',
    description: 'Desenvolver a arquitetura de agrupadores de material para gerir variações como cor e tamanho de forma individualizada, mantendo a vinculação a um catálogo global com saldo granular por variação.',
    demandType: 'story',
    classOfService: 'tech-debt',
    baseValue: 3200,
    effortAnalysis: 3,
    effortDev: 5,
    effortTest: 3,
    deadlineDays: 8,
    penaltyPerDay: 380,
  },
  {
    id: 'erp-stk-02',
    module: 'stock',
    moduleLabel: '📦 Estoque & Suprimentos',
    title: 'Fluxo de Homologação Técnica de Novos Materiais',
    description: 'Implementar um workflow de aprovação obrigatória onde novos insumos passam por triagem técnica e fiscal antes de serem liberados para movimentações de compra ou faturamento.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2400,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 280,
  },
  {
    id: 'erp-stk-03',
    module: 'stock',
    moduleLabel: '📦 Estoque & Suprimentos',
    title: 'Gestão de Unidades Secundárias e Conversão Automática',
    description: 'Desenvolver o motor de conversão de unidades de medida (ex: compra em caixas e venda fracionada em unidades), mantendo a integridade do saldo e do custo médio independentemente da embalagem.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2700,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 320,
  },
  {
    id: 'erp-stk-04',
    module: 'stock',
    moduleLabel: '📦 Estoque & Suprimentos',
    title: 'Controle de Embalagens Retornáveis e Vasilhames de Terceiros',
    description: 'Criar subsistema para rastrear a circulação de vasilhames, paletes e embalagens retornáveis que saem com mercadorias e geram pendências de devolução na logística.',
    demandType: 'support',
    classOfService: 'standard',
    baseValue: 2100,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 250,
  },
  {
    id: 'erp-stk-05',
    module: 'stock',
    moduleLabel: '📦 Estoque & Suprimentos',
    title: 'Rotina de Inventário Físico e Ajuste por Divergência',
    description: 'Automatizar o processo de lançamento de contagens físicas de estoque, apurando divergências entre o saldo contábil e o real para gerar ajustes automáticos de acuracidade.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 3000,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 400,
  },
  {
    id: 'erp-stk-06',
    module: 'stock',
    moduleLabel: '📦 Estoque & Suprimentos',
    title: 'Sugestão de Compras por Ponto de Pedido',
    description: 'Implementar algoritmo de sugestão de aquisição de mercadorias com base no histórico de giro, tempo de reposição do fornecedor e parâmetros de estoque mínimo.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2800,
    effortAnalysis: 3,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 8,
    penaltyPerDay: 320,
  },
  {
    id: 'erp-stk-07',
    module: 'stock',
    moduleLabel: '📦 Estoque & Suprimentos',
    title: 'Rastreamento de Lotes e Validade de Perecíveis',
    description: 'Desenvolver o controle de rastreabilidade por número de lote e data de validade, aplicando regras de saída baseadas em critérios de vencimento para evitar perdas no estoque.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 3300,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 3,
    deadlineDays: 7,
    penaltyPerDay: 450,
  },

  // =========================================================================
  // 🛒 Módulo de Inteligência de Vendas e CRM (7 cards)
  // =========================================================================
  {
    id: 'erp-sal-01',
    module: 'sales',
    moduleLabel: '🛒 Vendas & CRM',
    title: 'Painel de Análise Comercial e Margem Bruta Instantânea',
    description: 'Construir dashboard gerencial integrado com as frentes de caixa e vendas, exibindo o faturamento por turno e operador em contraponto direto ao custo de aquisição para calcular a margem em tempo real.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 3100,
    effortAnalysis: 3,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 8,
    penaltyPerDay: 350,
  },
  {
    id: 'erp-sal-02',
    module: 'sales',
    moduleLabel: '🛒 Vendas & CRM',
    title: 'Histórico de Relacionamento e Gestão de Contatos (CRM)',
    description: 'Implementar módulo de agendamentos e registro de interações com clientes, garantindo a preservação da memória institucional e o acompanhamento de prospecções comerciais.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2500,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 280,
  },
  {
    id: 'erp-sal-03',
    module: 'sales',
    moduleLabel: '🛒 Vendas & CRM',
    title: 'Gestão de Ausências e Redistribuição de Carteira de Vendedores',
    description: 'Criar rotina para gerenciar períodos de férias e afastamentos da equipe comercial, impedindo o direcionamento de leads a inativos e redistribuindo os clientes automaticamente.',
    demandType: 'support',
    classOfService: 'standard',
    baseValue: 2000,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 220,
  },
  {
    id: 'erp-sal-04',
    module: 'sales',
    moduleLabel: '🛒 Vendas & CRM',
    title: 'Motor de Promoções e Descontos Progressivos Automatizados',
    description: 'Desenvolver regras de negócio que aplicam descontos dinâmicos baseados no volume de compra ou recorrência do cliente, validando previamente os limites mínimos de margem permitidos.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 3400,
    effortAnalysis: 3,
    effortDev: 5,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 420,
  },
  {
    id: 'erp-sal-05',
    module: 'sales',
    moduleLabel: '🛒 Vendas & CRM',
    title: 'Painel Logístico de Rastreamento de Entrega de Pedidos',
    description: 'Implementar acompanhamento completo do ciclo de vida do pedido de venda, desde a separação no estoque e faturamento até a confirmação de entrega ao cliente final.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2900,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 330,
  },
  {
    id: 'erp-sal-06',
    module: 'sales',
    moduleLabel: '🛒 Vendas & CRM',
    title: 'Bloqueio Automático de Vendas para Clientes Inadimplentes',
    description: 'Desenvolver travas no faturamento que impedem a emissão de novos pedidos para clientes com títulos em aberto acima do limite de tolerância ou dias de atraso permitidos.',
    demandType: 'story',
    classOfService: 'expedite',
    baseValue: 3200,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 5,
    penaltyPerDay: 500,
  },
  {
    id: 'erp-sal-07',
    module: 'sales',
    moduleLabel: '🛒 Vendas & CRM',
    title: 'Orçamentos Comerciais com Validade e Conversão de Pedido',
    description: 'Criar rotina de orçamentos com prazo de validade estipulado, permitindo converter a proposta comercial diretamente em pedido de venda sem redigitação de itens.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2600,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 300,
  },

  // =========================================================================
  // ⚖️ Módulo Fiscal, Tributário e Governança (6 cards)
  // =========================================================================
  {
    id: 'erp-fisc-01',
    module: 'fiscal',
    moduleLabel: '⚖️ Fiscal & Tributário',
    title: 'Emissão e Controle de Sequência de Cartas de Correção Eletrônica',
    description: 'Desenvolver subsistema para retificação de documentos fiscais autorizados, garantindo o controle rigoroso da sequência de correções exigida pelos órgãos fiscalizadores.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 2800,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 400,
  },
  {
    id: 'erp-fisc-02',
    module: 'fiscal',
    moduleLabel: '⚖️ Fiscal & Tributário',
    title: 'Gerador de Arquivos para Obrigações Acessórias e SPED',
    description: 'Construir o motor de consolidação e exportação de dados tributários e de inventário, realizando pré-validações de consistência antes da geração dos arquivos magnéticos oficiais.',
    demandType: 'docs',
    classOfService: 'fixed-date',
    baseValue: 0,
    effortAnalysis: 3,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 0,
    accumulatedDocCost: 450,
    docCostPerDay: 200,
  },
  {
    id: 'erp-fisc-03',
    module: 'fiscal',
    moduleLabel: '⚖️ Fiscal & Tributário',
    title: 'Gestão e Aplicação de Benefícios e Incentivos Fiscais',
    description: 'Criar repositório de regras tributárias para tratamento automatizado de reduções de base de cálculo e isenções específicas por tipo de operação ou região de destino.',
    demandType: 'story',
    classOfService: 'fixed-date',
    baseValue: 3500,
    effortAnalysis: 3,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 480,
  },
  {
    id: 'erp-fisc-04',
    module: 'fiscal',
    moduleLabel: '⚖️ Fiscal & Tributário',
    title: 'Trilha de Auditoria e Log de Alterações em Cadastros Sensíveis',
    description: 'Implementar rastreabilidade completa de segurança registrando quem alterou, quando e o que foi modificado em cadastros críticos de preços, pessoas e parâmetros fiscais.',
    demandType: 'docs',
    classOfService: 'standard',
    baseValue: 0,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 8,
    penaltyPerDay: 0,
    accumulatedDocCost: 400,
    docCostPerDay: 180,
  },
  {
    id: 'erp-fisc-05',
    module: 'fiscal',
    moduleLabel: '⚖️ Fiscal & Tributário',
    title: 'Matriz de Tributação Cruzando Origem, Destino e NCM',
    description: 'Desenvolver o motor fiscal que calcula as alíquotas aplicáveis cruzando a classificação do produto com o estado de origem e destino da mercadoria transacionada.',
    demandType: 'story',
    classOfService: 'tech-debt',
    baseValue: 3600,
    effortAnalysis: 3,
    effortDev: 5,
    effortTest: 3,
    deadlineDays: 8,
    penaltyPerDay: 450,
  },
  {
    id: 'erp-fisc-06',
    module: 'fiscal',
    moduleLabel: '⚖️ Fiscal & Tributário',
    title: 'Cálculo e Destaque de Retenções de Impostos na Venda',
    description: 'Automatizar o destaque de impostos retidos na fonte (como tributos federais e sociais) diretamente nos itens do pedido de acordo com o perfil jurídico do cliente.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2700,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 320,
  },

  // =========================================================================
  // ⚡ Módulo de Frente de Caixa e Infraestrutura (5 cards)
  // =========================================================================
  {
    id: 'erp-pos-01',
    module: 'pos',
    moduleLabel: '⚡ Frente de Caixa & Infra',
    title: 'Importação e Consolidação de Faturamento Diário de ECFs',
    description: 'Desenvolver rotina fiscal para processar e unificar os dados de faturamento diário vindos de emissores de cupom fiscal e totalizadores eletrônicos.',
    demandType: 'support',
    classOfService: 'standard',
    baseValue: 2300,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 260,
  },
  {
    id: 'erp-pos-02',
    module: 'pos',
    moduleLabel: '⚡ Frente de Caixa & Infra',
    title: 'Autenticação Biométrica para Liberação de Operações de Risco',
    description: 'Integrar validação por biometria de pessoas autorizadas para liberar transações sensíveis no sistema, como cancelamentos, descontos extremos ou estornos financeiros.',
    demandType: 'story',
    classOfService: 'expedite',
    baseValue: 3100,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 5,
    penaltyPerDay: 480,
  },
  {
    id: 'erp-pos-03',
    module: 'pos',
    moduleLabel: '⚡ Frente de Caixa & Infra',
    title: 'Central Proativa de Alertas e Notificações de Negócio',
    description: 'Criar motor de monitoramento de eventos críticos no sistema (como estoque mínimo atingido ou contas vencidas), disparando avisos em tempo real para os responsáveis.',
    demandType: 'support',
    classOfService: 'standard',
    baseValue: 2500,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 300,
  },
  {
    id: 'erp-pos-04',
    module: 'pos',
    moduleLabel: '⚡ Frente de Caixa & Infra',
    title: 'Repositório Centralizado de Documentação Digital e Anexos',
    description: 'Implementar funcionalidade de gestão documental para associar arquivos digitais e contratos diretamente às entidades do sistema, controlando o tamanho e otimizando o banco de dados.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2800,
    effortAnalysis: 2,
    effortDev: 4,
    effortTest: 2,
    deadlineDays: 7,
    penaltyPerDay: 320,
  },
  {
    id: 'erp-pos-05',
    module: 'pos',
    moduleLabel: '⚡ Frente de Caixa & Infra',
    title: 'Configuração de Parâmetros Globais por Estação de Trabalho',
    description: 'Permitir a definição dinâmica de perfis operacionais, impressoras padrão, contas contábeis e almoxarifados vinculados especificamente a cada terminal de atendimento ou caixa da empresa.',
    demandType: 'story',
    classOfService: 'standard',
    baseValue: 2700,
    effortAnalysis: 2,
    effortDev: 3,
    effortTest: 2,
    deadlineDays: 6,
    penaltyPerDay: 310,
  },
];

/**
 * Returns a random ERP card template from the 32 business items
 */
export function getRandomErpCardTemplate(): ErpCardTemplate {
  const idx = Math.floor(Math.random() * ERP_BUSINESS_CATALOG.length);
  return ERP_BUSINESS_CATALOG[idx];
}
